### ISSUE TITLE
关于Apple TV版本Simple Live介绍错误

### ISSUE THREAD

**Issue by pcccccc** [ssnhd/tv#1]
1、Simple Live的github地址错误， 介绍里面贴的是Flutter版本的，和Apple TV版本并不是一个作者。正确地址应为：https://github.com/pcccccc/SimpleLiveTVOS

2、截图并非最新。

**Comment by pcccccc** [comment]
有时间的情况下希望更正

**Comment by ssnhd** [comment]
已更正

**Comment by pcccccc** [comment]
<img width="678" alt="image" src="https://github.com/user-attachments/assets/d67fb3ba-679b-412a-895c-97ca71b8996d">
这里还是有点小问题
